version: '3.8'
services:
  command-share:
    build: .
    ports:
      - "51753:51753"
    restart: unless-stopped
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
